default: &default
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  username: root
  password:
  host: localhost
  pool: 5
  timeout: 5000

development:
  database: api_cache_development
  <<: *default

test:
  database: api_cache_test
  <<: *default

production:
  database: api_cache_production
  <<: *default
